name: Build and deploy to AWS Ec2 using SSH - Environments

# on:
#   push:
#     branches:
#       - dev
#       - staging
#       - master

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.0
      
      - name: Maven Build
        run: |
          mvn --version
          mvn clean package
      - name: Build the Docker image
        run: docker build --tag vigneshsweekaran/hello-world-github-actions:$GITHUB_RUN_NUMBER .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push vigneshsweekaran/hello-world-github-actions:$GITHUB_RUN_NUMBER
  DeployDev:
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Deploying to Dev environment
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ github.run_number }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: TAG
          script: |
            docker rm -f hello-world-dev || true
            docker run --name hello-world-dev -d -p 9003:8080 vigneshsweekaran/hello-world-github-actions:$TAG
  DeployStaging:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.ref == 'refs/heads/staging' }}
    steps:
      - name: Deploying to Staging environment
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ github.run_number }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: TAG
          script: |
            docker rm -f hello-world-staging || true
            docker run --name hello-world-staging -d -p 9004:8080 vigneshsweekaran/hello-world-github-actions:$TAG
  DeployProd:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:   
      - name: Deploying to Prod environment
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ github.run_number }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: TAG
          script: |
            docker rm -f hello-world-prod || true
            docker run --name hello-world-prod -d -p 9005:8080 vigneshsweekaran/hello-world-github-actions:$TAG
