name: Matrix example with additional variables for matrix

# on:
#   push:
#     branches:
#       - dev
#       - staging
#       - master

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.0
      
      - name: Maven Build
        run: |
          mvn --version
          mvn clean package
      - name: Build the Docker image
        run: docker build --tag vigneshsweekaran/hello-world-github-actions:$GITHUB_RUN_NUMBER .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push vigneshsweekaran/hello-world-github-actions:$GITHUB_RUN_NUMBER

  pre-deploy:
    name: Pre-Deploy
    needs: build
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.get-environment.outputs.environment-name }}
    steps:
      - name: Determine Environment
        id: get-environment
        shell: python
        run: |
          import os
          env = 'none'
          if os.environ['GITHUB_REF'] == 'refs/heads/dev':
            env = 'dev'
          elif os.environ['GITHUB_REF'].startswith('refs/heads/feature/'):
            env = 'dev'
          elif os.environ['GITHUB_REF'] == 'refs/heads/staging':
            env = 'staging'
          elif os.environ['GITHUB_REF'] == 'refs/heads/master':
            env = 'prod'
          print('::set-output name=environment-name::' + env)

  Deploy:
    runs-on: ubuntu-latest
    needs: pre-deploy
    name: Deploy to ${{ needs.pre-deploy.outputs.environment-name }}
    environment: ${{ needs.pre-deploy.outputs.environment-name }}
    if: ${{ needs.pre-deploy.outputs.environment-name != 'none' }}
    strategy:
      matrix:
        no-env: [1, 2]
        include:
          - no-env: 1
            HOST: HOST1
            USERNAME: USERNAME1
            KEY: KEY1
          - no-env: 2
            HOST: HOST2
            USERNAME: USERNAME2
            KEY: KEY2
    steps:
      - name: Deploying to Dev environment
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ github.run_number }}
        with:
          host: ${{ secrets[matrix.HOST] }}
          username: ${{ secrets[matrix.USERNAME] }}
#           username: ${{ format('secrets.{0}', matrix.USERNAME) }}
          key: ${{ secrets[matrix.KEY] }}
          envs: TAG
          script: |
            docker rm -f hello-world-dev || true
            docker run --name hello-world-${{ needs.pre-deploy.outputs.environment-name }} -d -p 9003:8080 vigneshsweekaran/hello-world-github-actions:$TAG
